
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - awsresource.jsbarber.net
  resources:
  - vpces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - awsresource.jsbarber.net
  resources:
  - vpces/finalizers
  verbs:
  - update
- apiGroups:
  - awsresource.jsbarber.net
  resources:
  - vpces/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - v1
  resources:
  - service
  verbs:
  - get
  - list
  - watch
