# permissions for end users to view vpces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vpce-viewer-role
rules:
- apiGroups:
  - awsresource.jsbarber.net
  resources:
  - vpces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - awsresource.jsbarber.net
  resources:
  - vpces/status
  verbs:
  - get
